steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/juyun-juyunlifang/restaurant-guide-service:latest', '-f', 'service/Dockerfile', '.']
images:
  - 'gcr.io/juyun-juyunlifang/restaurant-guide-service:latest'

